jobs:
  provision:
    name: Provision
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkUserMember
      name: Check CI/CD team membership
      uses: tspascoal/get-user-teams-membership@v2
      with:
        GITHUB_TOKEN: ${{ secrets._TEMP_ACCESS_TOKEN_FOR_READING_ORG_TEAMS }}
        organization: openremote
        team: CI/CD
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        ACCOUNT_NAME: ${{ github.event.inputs.ACCOUNT_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets._TEMP_AWS_ACCESS_KEY_ID }}
        AWS_ROLE_NAME: ${{ secrets._TEMP_AWS_ROLE_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets._TEMP_AWS_SECRET_ACCESS_KEY }}
        DISK_SIZE: ${{ github.event.inputs.DISK_SIZE }}
        ELASTIC_IP: ${{ github.event.inputs.ELASTIC_IP }}
        HOST: ${{ github.event.inputs.HOST }}
        INSTANCE_TYPE: ${{ github.event.inputs.INSTANCE_TYPE }}
        PROVISION_S3_BUCKET: ${{ github.event.inputs.PROVISION_S3_BUCKET }}
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      name: Provision Host
      run: 'chmod +x .ci_cd/aws/*

        .ci_cd/aws/provision_host.sh "$ACCOUNT_NAME" "$HOST" "$INSTANCE_TYPE" "$DISK_SIZE"
        "$ELASTIC_IP" "$PROVISION_S3_BUCKET"

        '
name: Provision Host
on:
  repository_dispatch:
    types: trigger-ga___provision-host.yml
