jobs:
  provision:
    name: Provision
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkUserMember
      name: Check CI/CD team membership
      uses: tspascoal/get-user-teams-membership@v2
      with:
        GITHUB_TOKEN: ${{ secrets._TEMP_ACCESS_TOKEN_FOR_READING_ORG_TEAMS }}
        organization: openremote
        team: CI/CD
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        ACCOUNT_NAME: ${{ github.event.inputs.ACCOUNT_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets._TEMP_AWS_ACCESS_KEY_ID }}
        AWS_ROLE_NAME: ${{ secrets._TEMP_AWS_ROLE_NAME }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets._TEMP_AWS_SECRET_ACCESS_KEY }}
        HOSTED_DNS: ${{ github.event.inputs.HOSTED_DNS }}
        OU: ${{ github.event.inputs.OU }}
        PARENT_DNS_ZONE: ${{ github.event.inputs.PARENT_DNS_ZONE }}
        VPC_PEER: ${{ github.event.inputs.VPC_PEER }}
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      name: Provision Account
      run: 'chmod +x .ci_cd/aws/*

        .ci_cd/aws/provision_account.sh "$OU" "$ACCOUNT_NAME" "$PARENT_DNS_ZONE" "$HOSTED_DNS"
        "$VPC_PEER"

        '
name: Provision Account
on:
  repository_dispatch:
    types: trigger-ga___provision-account.yml
