jobs:
  provision:
    name: Start
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        ACTION: ${{ github.event.inputs.ACTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets._TEMP_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets._TEMP_AWS_SECRET_ACCESS_KEY }}
        HOST: ${{ github.event.inputs.HOST }}
      name: Perform Action
      run: 'chmod +x .ci_cd/aws/*

        .ci_cd/aws/start_stop_host.sh "$ACTION" "$HOST"

        '
name: Start/Stop Host
on:
  repository_dispatch:
    types: trigger-ga___start-stop-host.yml
